project_id = "wgdeakaftkjjcnsmsfap"

[functions.create-team-member]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false